name: Automate TfL Data Pipeline

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_and_insert_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run the data pipeline script
        env:
          DB_URI: ${{ secrets.DB_URI }}
        run: python scripts/tfl_pipeline.py
